
export type PersonaType = 'Technical' | 'Wellness' | 'Creative' | 'Academic' | 'Health' | 'Language' | 'Business' | 'Leisure';
export type Language = 'en' | 'zh';
export type ThemePreset = 'lumina' | 'lumina-light' | 'facebook' | 'wechat' | 'retro80s' | 'gameboy';

export interface UserProfile {
  id: string;
  username: string;
  name: string;
  avatar: string;
  bio: string;
}

export interface AIDigitalHuman {
  id: string;
  name: string;
  type: PersonaType;
  title: string;
  bio: string;
  avatar: string;
  online: boolean;
  systemInstruction: string;
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  text: string;
  timestamp: string;
  isAI: boolean;
  /** 语音消息播放 URL（与测试聊天一致） */
  audioUrl?: string;
  /** 发送者头像 URL（群聊中每个 AI 有不同头像） */
  senderAvatar?: string;
  /** 附件（图片/文档） */
  attachments?: { type: string; token?: string; url?: string; download_url?: string; preview_url?: string; name?: string; size?: number }[];
}

export interface ChatSession {
  id: string;
  title: string;
  participants: string[]; // AI IDs
  messages: Message[];
  lastMessageTime: string;
  isGroup: boolean;
  isTopicChat?: boolean;
  topic?: string;
  titleAutoGenerated?: boolean;
}

export interface MomentPost {
  id: string;
  authorId: string;
  authorName: string;
  authorAvatar: string;
  isAI: boolean;
  content: string;
  image?: string;
  imageUrls?: string[];
  thumbnailUrls?: string[];
  videoUrls?: string[];
  timestamp: string;
  likes: string[];
  /** 点赞总数（来自 API） */
  likeCount?: number;
  /** 当前用户是否已点赞 */
  likedByMe?: boolean;
  comments: {
    id: string;
    authorName: string;
    text: string;
  }[];
}

export type View = 'auth' | 'discovery' | 'messages' | 'moments' | 'contacts' | 'shared_agent';

/** URL 路径与视图映射：聊天 /messages、好友 /contacts、发现 /discovery、朋友圈 /moments */
export const VIEW_PATHS: Record<Exclude<View, 'auth' | 'shared_agent'>, string> = {
  discovery: '/discovery',
  messages: '/messages',
  contacts: '/contacts',
  moments: '/moments',
};

export function getShareTokenFromPath(pathname: string): string | null {
  const match = pathname.match(/^\/sharedAgent\/([^/]+)/);
  return match ? match[1] : null;
}

export function getViewFromPath(pathname: string): Exclude<View, 'auth'> {
  const p = pathname.replace(/\/$/, '') || '/';
  if (p === '/messages') return 'messages';
  if (p === '/contacts') return 'contacts';
  if (p === '/moments') return 'moments';
  if (p.startsWith('/sharedAgent/')) return 'shared_agent';
  return 'discovery';
}

export interface ThemeConfig {
  preset: ThemePreset;
  primaryColor: string;
  surfaceColor: string;
  backgroundColor: string;
  secondaryColor: string;
  textColor: string;
  borderRadius: 'none' | 'small' | 'medium' | 'large' | 'full';
  fontFamily: string;
  baseFontSize: string;
}
